on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      display_name:
        description: "Enter name to wish"
        default: "Hem"
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
     - name: "greetings"
       run: echo "Hare krishna ! ${{ inputs.display_name }}"
      
